extends: stylelint-config-standard
ignoreFiles:
  - node_modules/**/*

overrides:
  - files:
    - decks/nvim-regexplainer/*.css
    rules:
      csstools/use-nesting: always
  - files:
    - decks/*/components/*.css
    rules:
      csstools/use-nesting: never
  - files:
    - assets/*.css
    - _plugins/redhat-deck/redhat-theme.css
    rules:
      csstools/use-nesting: ignore

plugins:
  - stylelint-use-nesting
  - '@stylelistic/stylelint-plugin'

rules:
  alpha-value-notation: number # TODO: fix for `percentage` in tokens
  color-function-notation: legacy # TODO: fix for `modern` in tokens
  color-hex-length: long
  csstools/use-nesting: always
  custom-property-pattern: _?[a-z]+[a-z0-9-]*
  declaration-block-no-redundant-longhand-properties:
    - true
    - ignoreShorthands:
        - /grid/
  no-descending-specificity:
    - true
    - ignore:
      - selectors-within-list
  number-max-precision: 6
  selector-class-pattern: null
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-pseudo-element-colon-notation: single
  selector-pseudo-element-no-unknown:
    - true
    - ignorePseudoElements:
      - /part(.*)/
  selector-type-no-unknown:
    - true
    - ignore:
        - custom-elements
      ignoreTypes:
        - heading
        - actions
  shorthand-property-no-redundant-values: true

  '@stylistic/string-quotes': double
  '@stylistic/indentation': 2
  '@stylistic/max-line-length':
    - 100
    - ignorePattern: /--rh-font-family-/

