POST http://localhost:3333/
Content-Type: text/html
Accept: */*
---

<rh-accordion>
  <rh-accordion-header>Card</rh-accordion-header>
  <rh-accordion-panel>
    <rh-card>
      <h2 slot="header">Server Rendered Web Components</h2>
      <rh-cta slot="footer">
        <a href="#">Load 'em</a>
      </rh-cta>
    </rh-card>
  </rh-accordion-panel>
  <rh-accordion-header>Alert</rh-accordion-header>
  <rh-accordion-panel>
    <rh-alert><h3 slot="title">SSR</h3></rh-alert>
  </rh-accordion-panel>
</rh-accordion>
