name: Rebuild

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # 12:00 AM, only on Sunday

jobs:
  rebuild:
    runs-on: ubuntu-latest
    name: Rebuild site
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci --prefer-offline
      - run: npm run build

      - name: Publish to Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: npx netlify-cli deploy --prod --message "deploy from GitHub Action" --dir=_site

